package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuizUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuizUserAllPropertiesEquals(QuizUser expected, QuizUser actual) {
        assertQuizUserAutoGeneratedPropertiesEquals(expected, actual);
        assertQuizUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuizUserAllUpdatablePropertiesEquals(QuizUser expected, QuizUser actual) {
        assertQuizUserUpdatableFieldsEquals(expected, actual);
        assertQuizUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuizUserAutoGeneratedPropertiesEquals(QuizUser expected, QuizUser actual) {
        assertThat(expected)
            .as("Verify QuizUser auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuizUserUpdatableFieldsEquals(QuizUser expected, QuizUser actual) {
        assertThat(expected)
            .as("Verify QuizUser relevant properties")
            .satisfies(e -> assertThat(e.getNickname()).as("check nickname").isEqualTo(actual.getNickname()))
            .satisfies(e -> assertThat(e.getBio()).as("check bio").isEqualTo(actual.getBio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuizUserUpdatableRelationshipsEquals(QuizUser expected, QuizUser actual) {}
}
